Repository geopython/pywps, pull requests merged in 2018-12, with the labels that each got.

#424 Add KML mimetype
  pywps/inout/formats/__init__.py
Labels: enhancement

#426 added testing mode (#425)
  docs/configuration.rst
  pywps/app/Process.py
  pywps/configuration.py
Labels: enhancement

#428 Prepare release 4 2
  RELEASE-howto.md
  debian/changelog
Labels: documentation

#431 Bug fix 412
  pywps/inout/basic.py
  pywps/inout/formats/__init__.py
  pywps/inout/outputs.py
  pywps/templates/1.0.0/execute/main.xml
  tests/test_execute.py
  tests/test_inout.py
Labels: bug

#434 [WIP] update build / PyPI workflow
  .travis.yml
  MANIFEST.in
  requirements-dev.txt
  requirements.txt
  setup.py
Labels: bug, documentation, packaging

#439 update changelog 4.2.1
  debian/changelog
Labels: documentation

#440 Do not call Session.close_all
  pywps/dblog.py
Labels: bug
