Repository geopython/pywps, pull requests merged in 2019-04, with the labels that each got.

#462 Rename async to async_ for Python 3.7 compatibility.
  pywps/app/Process.py
Labels: bug

#464 fix for `allowed_values == AnyValue` in templates
  pywps/inout/inputs.py
  pywps/inout/literaltypes.py
  pywps/templates/1.0.0/describe/literal.xml
  tests/test_inout.py
Labels: bug

#465 fix sphinx build
  pywps/ext_autodoc.py
  pywps/inout/literaltypes.py
Labels: bug, documentation

#466 Add metalink support to facilitate outputs with multiple files
  docs/metalinkprocess.py
  docs/process.rst
  pywps/inout/basic.py
  pywps/inout/formats/__init__.py
  pywps/inout/outputs.py
  pywps/schemas/metalink/3.0/metalink.xsd
  pywps/schemas/metalink/4.0/metalink4.xsd
  pywps/schemas/metalink/4.0/xml.xsd
  pywps/templates/metalink/3.0/main.xml
  pywps/templates/metalink/4.0/main.xml
  pywps/validator/complexvalidator.py
  tests/processes/__init__.py
  tests/processes/metalinkprocess.py
  tests/test_execute.py
  tests/test_inout.py
Labels: enhancement

#467 fixed AllowedValue range
  pywps/inout/literaltypes.py
  pywps/validator/literalvalidator.py
  tests/validator/test_literalvalidators.py
Labels: bug

#468 Fix 406 user exceptions
  docs/api.rst
  docs/process.rst
  docs/show_error.py
  docs/wps.rst
  pywps/app/Process.py
  pywps/app/exceptions.py
Labels: enhancement

#470 added checksums argument to metalink class to make checksum computing…
  pywps/inout/outputs.py
  pywps/templates/metalink/3.0/main.xml
  pywps/templates/metalink/4.0/main.xml
  tests/test_inout.py
Labels: enhancement

#471 fixed ValuesReference implementation
  docs/api.rst
  pywps/inout/basic.py
  pywps/inout/inputs.py
  pywps/inout/literaltypes.py
  pywps/templates/1.0.0/describe/literal.xml
  pywps/validator/literalvalidator.py
  tests/test_describe.py
  tests/test_inout.py
  tests/test_literaltypes.py
  tests/validator/test_literalvalidators.py
Labels: enhancement
