Repository geopython/pywps, pull requests merged in 2019-11, with the labels that each got.

#501 fix release 4.2.3
  VERSION.txt
  debian/changelog
Labels: documentation

#451 Add AWS S3 Storage option + Process Status Store uses StorageAbstract
  .gitignore
  default-sample.cfg
  docs/configuration.rst
  docs/storage.rst
  pywps/app/Process.py
  pywps/configuration.py
  pywps/inout/basic.py
  pywps/inout/formats/__init__.py
  pywps/inout/outputs.py
  pywps/inout/storage/__init__.py
  pywps/inout/storage/builder.py
  pywps/inout/storage/file.py
  pywps/inout/storage/implementationbuilder.py
  pywps/inout/storage/s3.py
  pywps/response/execute.py
  requirements-s3.txt
  tests/__init__.py
  tests/test_filestorage.py
  tests/test_inout.py
  tests/test_s3storage.py
  tests/test_storage.py
  tox.ini
Labels: enhancement

#503 Issue 502 fix async
  .travis.yml
  pywps/app/Process.py
  pywps/inout/outputs.py
Labels: bug
