Repository geopython/pywps, pull requests merged in 2020-02, with the labels that each got.

#510 Add support for multiple languages
  docs/configuration.rst
  docs/process.rst
  pywps/app/Process.py
  pywps/app/WPSRequest.py
  pywps/inout/basic.py
  pywps/inout/inputs.py
  pywps/inout/outputs.py
  pywps/response/__init__.py
  pywps/response/capabilities.py
  pywps/response/describe.py
  pywps/response/execute.py
  pywps/templates/1.0.0/capabilities/main.xml
  pywps/templates/1.0.0/describe/main.xml
  pywps/templates/1.0.0/execute/main.xml
  pywps/tests.py
  pywps/translations.py
  tests/test_capabilities.py
  tests/test_describe.py
  tests/test_execute.py
  tests/test_inout.py
  tests/test_process.py
Labels: enhancement

#511 release 4.2.4
  VERSION.txt
  debian/changelog
Labels: documentation

#505 initial watchdog
  .codacy.yml
  .travis.yml
  alembic.ini
  docs/configuration.rst
  docs/deployment.rst
  docs/install.rst
  pywps/alembic/README.md
  pywps/alembic/__init__.py
  pywps/alembic/env.py
  pywps/alembic/fake_pywps.cfg
  pywps/alembic/script.py.mako
  pywps/alembic/versions/01d5298bfc61_add_process_column_to_request.py
  pywps/alembic/versions/eead25e2ad3a_create_tables.py
  pywps/app/Process.py
  pywps/app/Service.py
  pywps/app/WPSRequest.py
  pywps/application.py
  pywps/cli.py
  pywps/configuration.py
  pywps/dblog.py
  pywps/inout/inputs.py
  pywps/log.py
  pywps/processing/job.py
  pywps/queue.py
  pywps/response/__init__.py
  requirements.txt
  setup.cfg
  setup.py
  tests/test-pywps.cfg
  tests/test_dblog.py
  tests/test_processing.py
  tox.ini
Labels: enhancement

#519 fix tests with language option
  tests/test-pywps.cfg
  tests/test_capabilities.py
  tests/test_describe.py
  tests/test_execute.py
Labels: bug

#520 Issue 477 skip py27
  debian/control
  pywps/_compat.py
  pywps/app/Process.py
  pywps/app/Service.py
  pywps/app/WPSRequest.py
  pywps/exceptions.py
  pywps/ext_autodoc.py
  pywps/inout/basic.py
  pywps/inout/inputs.py
  pywps/inout/literaltypes.py
  pywps/inout/outputs.py
  pywps/inout/storage/__init__.py
  pywps/inout/storage/file.py
  pywps/inout/storage/implementationbuilder.py
  pywps/response/__init__.py
  pywps/response/execute.py
  pywps/validator/complexvalidator.py
  pywps/wpsserver.py
  requirements-dev.txt
  requirements.txt
  tests/test_execute.py
  tests/test_filestorage.py
  tests/test_inout.py
  tests/test_s3storage.py
  tox.ini
Labels: enhancement

#521 removed unused wpsserver.py
  pywps/inout/basic.py
  pywps/validator/complexvalidator.py
  pywps/wpsserver.py
  tests/test_ows.py
Labels: enhancement

#518 Issue 516 docs config
  default-sample.cfg
  docs/configuration.rst
  docs/deployment.rst
Labels: documentation
